Repository xtermjs/xterm.js, pull requests merged in 2019-04, with the labels that each got.

#1878 Utf32 buffer
  src/Buffer.test.ts
  src/Buffer.ts
  src/BufferLine.test.ts
  src/BufferLine.ts
  src/BufferReflow.ts
  src/CharWidth.test.ts
  src/InputHandler.test.ts
  src/InputHandler.ts
  src/Linkifier.test.ts
  src/Linkifier.ts
  src/SelectionManager.test.ts
  src/SelectionManager.ts
  src/Terminal.integration.ts
  src/Terminal.test.ts
  src/Terminal.ts
  src/Types.ts
  src/renderer/BaseRenderLayer.ts
  src/renderer/CharacterJoinerRegistry.test.ts
  src/renderer/CharacterJoinerRegistry.ts
  src/renderer/CursorRenderLayer.ts
  src/renderer/TextRenderLayer.ts
  src/renderer/dom/DomRendererRowFactory.test.ts
  src/renderer/dom/DomRendererRowFactory.ts
  src/ui/TestUtils.test.ts
Labels: area/performance, type/enhancement

#1993 Replace winptyCompat addon with windowsMode option
  demo/client.ts
  src/Buffer.ts
  src/Terminal.ts
  src/WindowsMode.ts
  src/addons/winptyCompat/Interfaces.ts
  src/addons/winptyCompat/package.json
  src/addons/winptyCompat/tsconfig.json
  src/addons/winptyCompat/winptyCompat.test.ts
  src/addons/winptyCompat/winptyCompat.ts
  src/tsconfig.all.json
  typings/xterm.d.ts
Labels: area/api, breaking-change

#1895 True color support
  src/Buffer.test.ts
  src/Buffer.ts
  src/BufferLine.test.ts
  src/BufferLine.ts
  src/BufferReflow.ts
  src/BufferSet.ts
  src/InputHandler.test.ts
  src/InputHandler.ts
  src/Terminal.test.ts
  src/Terminal.ts
  src/Types.ts
  src/renderer/BaseRenderLayer.ts
  src/renderer/CharacterJoinerRegistry.ts
  src/renderer/TextRenderLayer.ts
  src/renderer/dom/DomRendererRowFactory.test.ts
  src/renderer/dom/DomRendererRowFactory.ts
  src/ui/TestUtils.test.ts
Labels: area/renderer, type/enhancement
